language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
sudo: false
addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("GraphLayout")'
  - julia -e 'Pkg.test("GraphLayout"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("GraphLayout")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
